#!/bin/sh

# Usage: ./condor_matlab paramfile numjobs
project=$1
simulation=$2
offset=$3
nrjobs=$4
simid=$5
echo making dir condor/${project}/condor_log/${simulation}_${simid}
mkdir -p condor/${project}/condor_log/${simulation}_${simid}
#sed -r -e {s/OFFSET/$3/} -e {s/NRJOBS/$4/} -e {s/PARAM/$5/} condor/$project/$simulation.condor.submitfile > condor/$project/condor.submitfile
#condor_submit condor/$project/condor.submitfile
#rm condor/$project/condor.submitfile
